

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import {  Plus,List,Search,ChartColumnBig  } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ThemeProvider } from "@/components/theme-provider"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navigation = [
  
    { name: 'Despesas', href: '/invoices', current: false ,icon:<List/>},
    { name: 'Lançamentos', href: '/new', current: false, icon:<Plus/>}, 
    { name: 'Pesquisar', href: '/search', current: false ,icon:<Search />},
    { name: 'Dashboard', href: '/dashboard', current: false ,icon:<ChartColumnBig   />}
  ]

 



  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
  
        
        <main>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
      <nav className='scroll-m-1 justify-center border  p-1 '>
             <div className='flex grid-cols-1 gap-2 font-bold text-1xl mr-100 ml-150  mt-4 ' ><div className='flex grid-cols-1 ml-0 mr-50 mt-2'></div>
        {
        navigation.map((item)=>{
         return <a key={item.name} href={item.href} className='flex grid-cols-1 gap-1 text-sm font-medium'><div className={item.current ? 'text-gray-500  border-white delay-500' : ' text-gray-400 hover:text-sky-500 hover:border-y-sky-500  hover:border-b-2 delay-500'}><Button variant='ghost'  >{item.icon}{item.name}</Button></div> </a>
        })
      }
      
    </div>
     
    </nav>
          
            {children}
          </ThemeProvider>
        </main>
        
				
			
      </body>
    </html>
  );
}


