


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import {  Plus,List,Search,ChartColumnBig  } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { AppSidebar } from "@/components/app-sidebar"
import { ChartAreaInteractive } from "@/components/chart-area-interactive"
import { DataTable } from "@/components/data-table"
import { SectionCards } from "@/components/section-cards"
import { SiteHeader } from "@/components/site-header"
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"

import data from "@/lib/data.json"
import DashboardMain from "@/components/DashboardMain";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navigation = [
   
    { name: 'Dashboard', href: '/search', icon: <Search />, component: <DashboardMain /> },
  ]


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
  
        
        <main>
        <Toaster />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
     
        <SidebarProvider
             style={
               {
                 "--sidebar-width": "calc(var(--spacing) * 72)",
                 "--header-height": "calc(var(--spacing) * 12)",
               } as React.CSSProperties
             }
           >
             <AppSidebar />
             <SidebarInset>
               <SiteHeader />
              
               {children}
               
             </SidebarInset>
           </SidebarProvider>
    
          
           
          </ThemeProvider>
        </main>
        
				
			
      </body>
    </html>
  );
}


